name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: npm-cache-tests-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
