name: Test Commit

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: npm-cache-tests-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

  auto-merge:
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
